site_name: idkSIMULATION Documentation

nav:
  - Home: index.md
  - Description: descriptions.md
  - How to: main.md
  - Tipos: 
      - Parameters: parameters.md
      - Outputs: outputs.md
  - Preprocessing:
      - Profiling: profiling.md
  - Modelo: model.md
  - Main workflow: idksim.md
  - Postprocessing: postprocessing.md

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]
          options:
            show_private_members: true
            filters: []  # <--- ¡Esto permite mostrar TODO sin filtrar!

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.betterem
  - pymdownx.critic
